<a href="https://colab.research.google.com/github/awaiskhan005/DATA-SCIENCE-AND-AI-/blob/main/Heart_attack_ML_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import pandas as pd
import numpy as np

In [34]:
pip install ucimlrepo

In [35]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
heart_disease = fetch_ucirepo(id=45)

print(heart_disease)


{'data': {'ids': None, 'features':      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   45    1   1       110   264    0        0      132      0      1.2   
299   68    1   4       144   193    1        0      141      0      3.4   
300   57    1   4       130   131    0        0      115      1      1.2   
301   57    0   2       130   236    0        2      174      0      0.0   
302   38    1   3       138   175    0        0      173      0      0.0   

     slope   ca  thal  
0        3  0.0   6.0  
1   

In [36]:
df = pd.DataFrame(heart_disease.data.features)
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   45    1   1       110   264    0        0      132      0      1.2   
299   68    1   4       144   193    1        0      141      0      3.4   
300   57    1   4       130   131    0        0      115      1      1.2   
301   57    0   2       130   236    0        2      174      0      0.0   
302   38    1   3       138   175    0        0      173      0      0.0   

     slope   ca  thal  
0        3  0.0   6.0  
1        2  3.0   3.0  
2        2  2.0   7.0  
3        3  0.0   3.0  
4        1  0.0   3.0  
..     ...  ...   ...  
298      2  0.0   7.0  
299      2  2.0   7.0  
300      2  1.0   7.0  
301      2  1.0   3.0  
302      1  NaN   3.0  

[303 rows x 13 columns]

In [54]:
# prompt: fill all the values in the df

df.fillna(df.mean(), inplace=True)


In [55]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
dtype: int64

In [56]:
# prompt: fill the data of df by mode for catogorical and numercial by mean do for ca and thal

numerical_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
categorical_cols = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']

# Fill missing numerical columns with the mean
df[numerical_cols] = df[numerical_cols].fillna(df[numerical_cols].mean())

# Fill missing categorical columns with the mode
df[categorical_cols] = df[categorical_cols].fillna(df[categorical_cols].mode().iloc[0])


In [57]:
df2 = pd.DataFrame(heart_disease.data.targets)
df2

num
0      0
1      2
2      1
3      0
4      0
..   ...
298    1
299    2
300    3
301    1
302    0

[303 rows x 1 columns]

In [58]:
df2.isnull().sum()

num    0
dtype: int64

In [59]:
# data (as pandas dataframes)
X = heart_disease.data.features
y = heart_disease.data.targets

# metadata
print(heart_disease.metadata)

# variable information
print(heart_disease.variables)

{'uci_id': 45, 'name': 'Heart Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/45/heart+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/45/data.csv', 'abstract': '4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 303, 'num_features': 13, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['num'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1989, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C52P4X', 'creators': ['Andras Janosi', 'William Steinbrunn', 'Matthias Pfisterer', 'Robert Detrano'], 'intro_paper': {'title': 'International application of a new probability algorithm for the diagnosis of coronary artery disease.', 'authors': 'R. Detrano, A. Jánosi, W. Steinbrunn, M. Pfisterer, J. Schmid, S. Sa

In [60]:
X.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

    ca  thal  
0  0.0   6.0  
1  3.0   3.0  
2  2.0   7.0  
3  0.0   3.0  
4  0.0   3.0

In [61]:
y.head(5)

num
0    0
1    2
2    1
3    0
4    0

In [62]:
# prompt: how to split data into train and test

from sklearn.model_selection import train_test_split

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# Print the shapes of the training and test sets
print('X_train shape:', X_train.shape)
print('y_train shape:', y_train.shape)
print('X_test shape:', X_test.shape)
print('y_test shape:', y_test.shape)


X_train shape: (242, 13)
y_train shape: (242, 1)
X_test shape: (61, 13)
y_test shape: (61, 1)


In [63]:
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
132   29    1   2       130   204    0        2      202      0      0.0   
202   57    1   3       150   126    1        0      173      0      0.2   
196   69    1   1       160   234    1        2      131      0      0.1   
75    65    0   3       160   360    0        2      151      0      0.8   
176   52    1   4       108   233    1        0      147      0      0.1   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
188   54    1   2       192   283    0        2      195      0      0.0   
71    67    1   4       125   254    1        0      163      0      0.2   
106   59    1   4       140   177    0        0      162      1      0.0   
270   61    1   4       140   207    0        2      138      1      1.9   
102   57    0   4       128   303    0        2      159      0      0.0   

     slope   ca  thal  
132      1  0.0   3.0  
202      1  1.0   7.0  
196      2  1.0   3.0  
75       1  0.0   3.0  
176      1  3.0   7.0  
..     ...  ...   ...  
188      1  1.0   7.0  
71       2  2.0   7.0  
106      1  1.0   7.0  
270      1  1.0   7.0  
102      1  1.0   3.0  

[242 rows x 13 columns]

In [64]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   53    1   3       130   246    1        2      173      0      0.0   
228   54    1   4       110   206    0        2      108      1      0.0   
111   56    1   4       125   249    1        2      144      1      1.2   
246   58    1   4       100   234    0        0      156      0      0.1   
60    51    0   4       130   305    0        0      142      1      1.2   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
249   62    1   2       128   208    1        2      140      0      0.0   
104   49    1   3       120   188    0        0      139      0      2.0   
300   57    1   4       130   131    0        0      115      1      1.2   
193   62    0   4       138   294    1        0      106      0      1.9   
184   60    0   4       158   305    0        2      161      0      0.0   

     slope   ca  thal  
179      1  3.0   3.0  
228      2  1.0   3.0  
111      2  1.0   3.0  
246      1  1.0   7.0  
60       2  0.0   7.0  
..     ...  ...   ...  
249      1  0.0   3.0  
104      2  3.0   7.0  
300      2  1.0   7.0  
193      2  3.0   3.0  
184      1  0.0   3.0  

[61 rows x 13 columns]

In [65]:
y_train

num
132    0
202    0
196    0
75     0
176    0
..   ...
188    1
71     3
106    2
270    1
102    0

[242 rows x 1 columns]

In [66]:
y_test

num
179    0
228    3
111    1
246    2
60     2
..   ...
249    0
104    3
300    3
193    2
184    1

[61 rows x 1 columns]

In [68]:
X_train.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          3
thal        2
dtype: int64

In [69]:
# prompt: fill the catagorical data by mode and numerical data by mean in all train and test

# Fill missing numerical columns with the mean
X_train[numerical_cols] = X_train[numerical_cols].fillna(X_train[numerical_cols].mean())
X_test[numerical_cols] = X_test[numerical_cols].fillna(X_test[numerical_cols].mean())

# Fill missing categorical columns with the mode
X_train[categorical_cols] = X_train[categorical_cols].fillna(X_train[categorical_cols].mode().iloc[0])
X_test[categorical_cols] = X_test[categorical_cols].fillna(X_test[categorical_cols].mode().iloc[0])



In [70]:
# prompt: apply logistic regression

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Create a logistic regression model
model = LogisticRegression()

# Train the model on the training data
model.fit(X_train, y_train)

# Predict the labels for the test data
y_pred = model.predict(X_test)

# Calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Print the confusion matrix
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

# Print the classification report
print('Classification Report:')
print(classification_report(y_test, y_pred))


Accuracy: 0.5409836065573771
Confusion Matrix:
[[27  2  0  0  0]
 [ 6  4  0  2  0]
 [ 1  3  0  5  0]
 [ 1  2  2  2  0]
 [ 0  1  1  2  0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.93      0.84        29
           1       0.33      0.33      0.33        12
           2       0.00      0.00      0.00         9
           3       0.18      0.29      0.22         7
           4       0.00      0.00      0.00         4

    accuracy                           0.54        61
   macro avg       0.26      0.31      0.28        61
weighted avg       0.45      0.54      0.49        61



/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` param

In [71]:
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

Accuracy: 0.5409836065573771
